name: spendingtracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  theme_extensions_builder_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  theme_extensions_builder: ^2.0.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
