// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEVWC459-HEMtM00hNMgbw3IxC9d_jkE',
    appId: '1:585009479301:web:3a21ac33ed567903d6b3ec',
    messagingSenderId: '585009479301',
    projectId: 'money-tracker-95957',
    authDomain: 'money-tracker-95957.firebaseapp.com',
    storageBucket: 'money-tracker-95957.firebasestorage.app',
    measurementId: 'G-3RBT27KMP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ekXAhxIikM6sh-MHBfTgPW4bVoQWEIQ',
    appId: '1:585009479301:android:4ce24d7c9fee5eebd6b3ec',
    messagingSenderId: '585009479301',
    projectId: 'money-tracker-95957',
    storageBucket: 'money-tracker-95957.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LPPmb2XnK2hzKmqMgYFX31eJbBG1Z14',
    appId: '1:585009479301:ios:4dc03e87ca524197d6b3ec',
    messagingSenderId: '585009479301',
    projectId: 'money-tracker-95957',
    storageBucket: 'money-tracker-95957.firebasestorage.app',
    iosBundleId: 'com.example.spendingtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LPPmb2XnK2hzKmqMgYFX31eJbBG1Z14',
    appId: '1:585009479301:ios:4dc03e87ca524197d6b3ec',
    messagingSenderId: '585009479301',
    projectId: 'money-tracker-95957',
    storageBucket: 'money-tracker-95957.firebasestorage.app',
    iosBundleId: 'com.example.spendingtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLEVWC459-HEMtM00hNMgbw3IxC9d_jkE',
    appId: '1:585009479301:web:806553a14c226d5ad6b3ec',
    messagingSenderId: '585009479301',
    projectId: 'money-tracker-95957',
    authDomain: 'money-tracker-95957.firebaseapp.com',
    storageBucket: 'money-tracker-95957.firebasestorage.app',
    measurementId: 'G-7M32KNJ39W',
  );
}
